- Sources/SunXi.swift
Helper struct that will dynamically (and safely) calculate the GPIO pin number for any SunXi hardware (e.g. Orange Pi).
> Added SunXi GPIO Support

- Sources/SwiftyGPIO.swift
I was getting four warnings when building. Heading the warnings made them go away.
> Added .self to CChar for reference to metatype warnings.

- Sources/SwiftyGPIO.swift
Currently using [Swift Nightly's](https://swiftnightly.com/) 07-23 build for the Pi. `UnsafeMutablePointer.init(allocatingCapacity:)` has been replaced with `UnsafeMutablePointer.allocate(capacity: )` and `UnsafeMutablePointer.deallocateCapacity()` has been replaced with `UnsafeMutablePointer.deallocate(capacity: )`. I have made the according changes to SwiftyGPIO.swift
> UnsafeMutablePointer API Change

- Sources/SwiftyGPIO.swift
UnsafeMutableRawPointer.load function loads the value from memory instead of converting the type. This causes the Segmentation Fault.
> Fixing Seg Fault

- Sources/PWM.swift
Limiting `duty` to Int doesn't allow for fine positioning of the servo. This works very well for me after this small change (Raspberry Pi 3, Ubuntu Mate, Swift 3.1, Sparkfun small servo):
```
class Servo {
static let period = 20_000_000
let left: Double
let right: Double
let output: PWMOutput
init(left: Double, right: Double, output: PWMOutput) {
self.left = left
self.right = right
self.output = output
}
func move(_ position: Double) {
guard position >= 0 && position <= 1 else { return }
let duty = left + (right - left) * position
print("moving to duty \(duty)...")
output.startPWM(period: Servo.period, duty: duty)
}
}
let pwms = SwiftyGPIO.hardwarePWMs(for: .RaspberryPi3)!
let pwmSmall = (pwms[0]?[.P18])!
let servoSmall = Servo(left: 3, right: 12, output: pwmSmall)
var x = 0.0
let …
```
> Allow floating point duty in PWM.

- Sources/UART.swift
- Modernized tty naming ("serial0" / "serial1")
- Added 2400 / 4800 speeds
- Made open() nonblocking (fixes hang on open() call)
> UART adaptations for modern Raspbian

- Sources/I2C.swift
Fixed a bug in the i2c_smbus_write_block_data function, where the last item of the values array would be dismissed, due to incorrect boundaries in the for loop.
Fixed a bug in the i2c_smbus_write_block_data function, where the last item of the values array would be dismissed, due to incorrect boundaries in the for loop. The bounds of the range of the for loop would exclude the last value and therefore in combination with the i-1 statement dismiss the last element of the array. This is now fixed.
There is something wring with the i2c_smbus_read_block_data as well, like you mentioned in our slack chat, but I'm not certain what the exact problem is, so we might need to discuss that further before I can fix it.
> Bugfix i2c_smbus_write_block_data in I2C.swift

- Sources/SwiftyGPIO.swift
`value.characters` is deprecated starting w/ 3.2. (produces
a warning, which this change avoids).
> Fix warning in Swift 3.2+

- Package@swift-4.swift
- Sources/I2C.swift
- Sources/SwiftyGPIO.swift
Add a `Package@swift-4.swift`, so that the package
compiles in Swift 4 mode.
Port the I2C/SwiftyGPIO files to compile with
Swift 4.
Swift 3 should still work just fine!
> Add SPM 4 package manifest, port code to 4

- Sources/Mailbox.swift
Just making sure that this doesn't try to get compiled on non-linux platforms
> Don't compile this on non-linux platforms

- Sources/ADC.swift
This fixes a compiler warning with string API changes in Swift 3.1 and later
> Fix string describing warnings

- Sources/SunXi.swift
- Sources/SwiftyGPIO.swift
This feature adds `Codable` support to some of the public enums.
This is useful when a GPIO configuration needs to be serialized and sent over the network, for example: remote configuration.
This also fixes a warning in Xcode 10.2: `'public' modifier is redundant for enum declared in a public extension`.
> Make public enums codable and fix enum warning in Xcode 10.2

- Sources/SwiftyGPIO/Generic/UART.swift
Added missing return in init of UART.swift
> Init in UART.swift missing return

- README.md
- Sources/UART.swift
Adds a helper method to the `UARTInterface` protocol in order to help users to know whether there is available data on the UART serial port, or not.
Decided not to add the code to check for data availability in each of the current `read` methods so that users could decide if checking for availability is needed for them or not. 
The reason I added this method was because on the library I've been working on, there are some edge cases where data does not get send from one point to the other (or gets delayed) so whenever I called `readData`(and data was not there or delayed) my code would just get stuck in there forever. After some research, found out that [attempting to read from an empty pipe, by using **unistd**, **read** method, will block the process until data is …
> UART Data Availability

- Sources/1Wire.swift
- Sources/SPI.swift
- Sources/UART.swift
Addressing compiler warnings of using dangling pointers.
n/a
> Addressing compiler warnings of using dangling pointers

- Sources/ADC.swift
- Sources/I2C.swift
- Sources/PWM.swift
- Sources/SPI.swift
- Sources/SwiftyGPIO.swift
- Sources/UART.swift
> Gets rid of not needed fallthrough in switch statements

- Sources/SwiftyGPIO.swift
Refactor func makeInterruptThread of GPIO to avoid creating string instance
> Refactor func makeInterruptThread of GPIO to avoid creating string instance

- Sources/SwiftyGPIO.swift
Simplify switch using UInt8 instead of Character.asciiValue
> Simplify switch using UInt8 instead of Character.asciiValue

- README.md
- Sources/I2C.swift
- Sources/SwiftyGPIO.swift
Small change to add .RaspberryPi4 as a valid enum case for the same I2C interfaces as Pi3.  Without it, calls to `SwiftyGPIO.hardwareI2Cs(for:.RaspberryPi4)` will return nil, though the I2C implementation is valid for Pi4 and Pi4B.
There is also one small comment typo fix for what looks to be a copy/paste of Pi3 to Pi4 in the global enums.
Lastly a minor README add to mention Pi 4B support, which I have been using for general GPIO and I2C integration with PCA 9685 and GY-521 (MPU 6050) modules.
Tested with [MPU-6050.swift](https://github.com/uraimo/MPU-6050.swift) on default address (`0x68`)
Tested with [PCA9685](https://github.com/Kaiede/PCA9685.git) on default address (`0x40`)
```
0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- …
```
> Add .RaspberryPi4 as valid enum case for I2C interfaces

- Sources/SwiftyGPIO.swift
Describe the content of this pull request. 
When reading a file with fread, it is possible for it to return 0 if you reach the EOF which would cause removing the newline character to crash.
> On success, fread() and fwrite() return the number of items read
or written.  This number equals the number of bytes transferred
only when size is 1.  If an error occurs, or the end of the file
is reached, the return value is a short item count (or zero).
If it's a new feature, do you plan to create additional PRs based on this one in the future to add additional functionalities?
Is there something you are unsure of or something you'd like to discuss before merging the final version of this PR?
> Fix readFromFile removing newline when fread returns 0
